"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { Box, CheckCircle2, FileUp, ShieldCheck, Sparkles } from "lucide-react";
import { API_URL } from "@/lib/api";

type CreatedRequest={number:string;trackingCode:string;trackingUrl:string};

export default function RequestPage(){
  const [file,setFile]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [created,setCreated]=useState<CreatedRequest|null>(null);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const data=new FormData(event.currentTarget);if(file)data.set("file",file);try{const response=await fetch(`${API_URL}/api/public/requests`,{method:"POST",body:data});const body=await response.json();if(!response.ok)throw new Error(body.error||"Не удалось отправить заявку");setCreated(body)}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось отправить заявку")}finally{setBusy(false)}}
  if(created)return <main className="request-page"><section className="request-success"><span className="request-icon success"><CheckCircle2/></span><p className="eyebrow">ЗАЯВКА ПРИНЯТА</p><h1>Модель уже в мастерской</h1><p>Мы оценим печать и свяжемся с вами. Сохраните персональный код заказа.</p><strong className="tracking-code">{created.trackingCode}</strong><Link className="button primary" href={created.trackingUrl}>Открыть заказ {created.number}</Link></section></main>;
  return <main className="request-page"><header className="request-nav"><Link className="brand" href="/"><span className="brand-mark"><Box size={20}/></span>PrintForge</Link><span><ShieldCheck size={16}/> Файл доступен только мастерской</span></header><div className="request-layout"><section className="request-intro"><p className="eyebrow">ОНЛАЙН-ЗАЯВКА</p><h1>Превратим вашу 3D-модель <em>в готовую деталь.</em></h1><p>Загрузите STL, OBJ, 3MF или G-code. После отправки вы получите код, по которому видно стоимость, фотографии и каждый этап производства.</p><div className="request-benefits"><span><Sparkles/>Автоматический анализ файла</span><span><CheckCircle2/>Прозрачная стоимость и статусы</span></div></section><form className="request-form" onSubmit={submit}><div className="form-title"><span className="request-icon"><FileUp/></span><div><h2>Новая заявка</h2><p>Ответим после проверки модели</p></div></div><label>Ваше имя<input name="name" required placeholder="Иван Петров"/></label><div className="form-grid"><label>Email<input name="email" type="email" placeholder="name@example.com"/></label><label>Телефон<input name="phone" placeholder="+373 ..."/></label></div><label className="dropzone"><input name="file" type="file" required accept=".stl,.obj,.3mf,.gcode,.gco" onChange={event=>setFile(event.target.files?.[0]||null)}/><FileUp/><strong>{file?file.name:"Выберите 3D-файл"}</strong><span>STL, OBJ, 3MF или G-code</span></label><div className="form-grid"><label>Материал<select name="material" defaultValue="PLA"><option>PLA</option><option>PETG</option><option>ABS</option><option>ASA</option><option>TPU</option><option>Не знаю</option></select></label><label>Цвет<input name="color" placeholder="Чёрный"/></label></div><label>Количество<input name="quantity" type="number" min="1" defaultValue="1"/></label><label>Комментарий<textarea name="notes" rows={3} placeholder="Размер, прочность, срок или другие пожелания"/></label>{error&&<p className="form-error">{error}</p>}<button className="button primary submit-request" disabled={busy}>{busy?"Отправляем…":"Отправить модель в мастерскую"}</button></form></div></main>;
}
