"use client";

import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, Play, Plus, Zap } from "lucide-react";
import { api, duration, money } from "@/lib/api";
import { ErrorNote, Modal, PageHeader, Status } from "@/components/ui";

type Printer={id:string;name:string;manufacturer:string;powerWatts:number;purchasePrice:number;depreciationHours:number};
type Spool={id:string;code:string;material:string;colorName:string;initialWeightGrams:number;remainingWeightGrams:number;purchasePrice:number};
type Settings={electricityPricePerKwh:number;machineRatePerHour:number;labourRatePerHour:number;defaultMarkupPercent:number;currency:string};
type OrderChoice={id:string;number:string;customerName?:string;models:{id:string;name:string}[]};
type Job={id:string;status:string;quantity:number;estimatedMinutes:number;estimatedFilamentGrams:number;actualFilamentGrams?:number;powerWatts:number;estimatedEnergyKwh:number;actualEnergyKwh?:number;electricityCost:number;materialCost:number;machineCost:number;labourCost:number;postProcessingCost:number;packagingCost:number;otherCost:number;totalCost:number;suggestedPrice:number;printerName:string;spoolCode:string;material:string;colorName:string;orderNumber?:string;modelName?:string};

export default function Jobs(){
  const queryClient=useQueryClient();const [creating,setCreating]=useState(false);const [complete,setComplete]=useState<Job|null>(null);
  const jobs=useQuery({queryKey:["jobs"],queryFn:()=>api<Job[]>("/api/print-jobs")});
  const status=useMutation({mutationFn:({id,body}:{id:string;body:Record<string,unknown>})=>api(`/api/print-jobs/${id}/status`,{method:"PATCH",body:JSON.stringify(body)}),onSuccess:()=>{queryClient.invalidateQueries({queryKey:["jobs"]});queryClient.invalidateQueries({queryKey:["orders"]});queryClient.invalidateQueries({queryKey:["dashboard"]});setComplete(null)}});
  return <><PageHeader eyebrow="ПРОИЗВОДСТВО" title="Очередь печати" description="Планируйте задания, связывайте их с заказом и заранее видьте полную себестоимость." actions={<button className="button primary" onClick={()=>setCreating(true)}><Plus size={17}/>Рассчитать задание</button>}/>
    {creating&&<JobCreator onClose={()=>setCreating(false)} onCreated={()=>{setCreating(false);queryClient.invalidateQueries({queryKey:["jobs"]});queryClient.invalidateQueries({queryKey:["orders"]})}}/>}
    <div className="data-card table-wrap"><table className="table"><thead><tr><th>Задание</th><th>Принтер</th><th>Материал</th><th>Время / энергия</th><th>Себестоимость</th><th>Статус</th><th/></tr></thead><tbody>{jobs.data?.map(job=><tr key={job.id}><td><strong>{job.orderNumber||`PJ-${job.id.slice(0,8)}`}</strong><small>{job.modelName||"Без модели"} · {job.quantity} шт.</small></td><td>{job.printerName}</td><td><strong>{job.material} · {job.colorName}</strong><small>{job.spoolCode} · {job.estimatedFilamentGrams} г</small></td><td><strong>{duration(job.estimatedMinutes)}</strong><small><Zap size={10}/> {job.estimatedEnergyKwh.toFixed(3)} кВт·ч · {money(job.electricityCost)}</small></td><td><strong>{money(job.totalCost)}</strong><small>Цена: {money(job.suggestedPrice)}</small></td><td><Status value={job.status}/></td><td>{job.status==="QUEUED"&&<button className="icon-button" title="Запустить" onClick={()=>status.mutate({id:job.id,body:{status:"PRINTING"}})}><Play size={16}/></button>}{job.status==="PRINTING"&&<button className="icon-button" title="Завершить" onClick={()=>setComplete(job)}><Check size={16}/></button>}</td></tr>)}</tbody></table></div>
    {complete&&<Modal title="Завершить печать" onClose={()=>setComplete(null)}><form className="form-grid" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);status.mutate({id:complete.id,body:{status:"SUCCESS",actualMinutes:Number(data.get("minutes")),actualFilamentGrams:Number(data.get("grams")),actualEnergyKwh:data.get("energy")?Number(data.get("energy")):undefined}})}}><label className="field">Фактическое время, мин<input name="minutes" type="number" min="0" defaultValue={complete.estimatedMinutes} required/></label><label className="field">Фактический пластик, г<input name="grams" type="number" min="0" step=".01" defaultValue={complete.estimatedFilamentGrams} required/></label><label className="field full">Фактическая энергия, кВт·ч <small>Можно оставить пустым — рассчитаем по мощности и времени.</small><input name="energy" type="number" min="0" step="0.001" placeholder={complete.estimatedEnergyKwh.toFixed(3)}/></label>{status.error&&<div className="field full"><ErrorNote error={status.error}/></div>}<div className="form-actions"><button type="button" className="button" onClick={()=>setComplete(null)}>Отмена</button><button className="button primary" disabled={status.isPending}>Завершить и списать пластик</button></div></form></Modal>}
  </>;
}

function JobCreator({onClose,onCreated}:{onClose:()=>void;onCreated:()=>void}){
  const printers=useQuery({queryKey:["printers"],queryFn:()=>api<Printer[]>("/api/printers")});const spools=useQuery({queryKey:["spools"],queryFn:()=>api<Spool[]>("/api/spools")});const settings=useQuery({queryKey:["settings"],queryFn:()=>api<Settings>("/api/settings")});const orders=useQuery({queryKey:["orders"],queryFn:()=>api<OrderChoice[]>("/api/orders")});
  const [orderId,setOrderId]=useState("");const [modelId,setModelId]=useState("");const [values,setValues]=useState({printerId:"",spoolId:"",minutes:270,grams:184,labour:.5,post:0,packaging:10,other:0,markup:40});
  const [scheduledStart,setScheduledStart]=useState("");
  const create=useMutation({mutationFn:(body:Record<string,unknown>)=>api("/api/print-jobs",{method:"POST",body:JSON.stringify(body)}),onSuccess:onCreated});
  const selectedOrder=orders.data?.find(order=>order.id===orderId);const printer=printers.data?.find(item=>item.id===values.printerId)??printers.data?.[0];const spool=spools.data?.find(item=>item.id===values.spoolId)??spools.data?.[0];const config=settings.data;
  const cost=useMemo(()=>{const hours=values.minutes/60;const energy=(printer?.powerWatts??0)/1000*hours;const material=values.grams*((spool?.purchasePrice??0)/(spool?.initialWeightGrams||1));const machine=hours*(config?.machineRatePerHour??0)+hours*((printer?.purchasePrice??0)/(printer?.depreciationHours||1));const labour=values.labour*(config?.labourRatePerHour??0);const electricity=energy*(config?.electricityPricePerKwh??0);const total=material+machine+labour+electricity+values.post+values.packaging+values.other;return{energy,material,machine,labour,electricity,total,price:total*(1+values.markup/100)}},[values,printer,spool,config]);
  function numberValue(key:keyof typeof values,value:string){setValues(current=>({...current,[key]:Number(value)}))}
  function submit(){if(!printer||!spool)return;create.mutate({orderId:orderId||null,modelId:modelId||null,printerId:printer.id,spoolId:spool.id,quantity:1,estimatedMinutes:values.minutes,estimatedFilamentGrams:values.grams,labourHours:values.labour,postProcessingCost:values.post,packagingCost:values.packaging,otherCost:values.other,markupPercent:values.markup,scheduledStart:scheduledStart?new Date(scheduledStart).toISOString():null})}
  return <div className="cost-layout"><div className="settings-section"><h2>Параметры печати</h2><p>Расчёт обновляется сразу. Статус связанного заказа попадёт клиенту и в Telegram.</p><div className="form-grid">
    <label className="field">Заказ<select value={orderId} onChange={event=>{setOrderId(event.target.value);setModelId("")}}><option value="">Без заказа</option>{orders.data?.map(order=><option value={order.id} key={order.id}>{order.number} · {order.customerName||"без клиента"}</option>)}</select></label>
    <label className="field">Модель заказа<select value={modelId} onChange={event=>setModelId(event.target.value)} disabled={!selectedOrder}><option value="">Без модели</option>{selectedOrder?.models.map(model=><option value={model.id} key={model.id}>{model.name}</option>)}</select></label>
    <label className="field">Принтер<select value={values.printerId||printer?.id||""} onChange={event=>setValues(current=>({...current,printerId:event.target.value}))}><option value="">Выберите</option>{printers.data?.map(item=><option value={item.id} key={item.id}>{item.manufacturer} {item.name} · {item.powerWatts} Вт</option>)}</select></label>
    <label className="field">Катушка<select value={values.spoolId||spool?.id||""} onChange={event=>setValues(current=>({...current,spoolId:event.target.value}))}><option value="">Выберите</option>{spools.data?.map(item=><option value={item.id} key={item.id}>{item.code} · {item.material} {item.colorName} · {item.remainingWeightGrams} г</option>)}</select></label>
    <label className="field">Время, минут<input type="number" min="0" value={values.minutes} onChange={event=>numberValue("minutes",event.target.value)}/></label><label className="field">Пластик, г<input type="number" min="0" step=".01" value={values.grams} onChange={event=>numberValue("grams",event.target.value)}/></label><label className="field full">Запланированный старт<input type="datetime-local" value={scheduledStart} onChange={event=>setScheduledStart(event.target.value)}/></label><label className="field">Работа оператора, ч<input type="number" min="0" step=".1" value={values.labour} onChange={event=>numberValue("labour",event.target.value)}/></label><label className="field">Постобработка<input type="number" min="0" step=".01" value={values.post} onChange={event=>numberValue("post",event.target.value)}/></label><label className="field">Упаковка<input type="number" min="0" step=".01" value={values.packaging} onChange={event=>numberValue("packaging",event.target.value)}/></label><label className="field">Прочее<input type="number" min="0" step=".01" value={values.other} onChange={event=>numberValue("other",event.target.value)}/></label><label className="field full">Наценка, %<input type="number" min="0" step="1" value={values.markup} onChange={event=>numberValue("markup",event.target.value)}/></label>
  </div>{create.error&&<ErrorNote error={create.error}/>}<div className="form-actions" style={{marginTop:20}}><button className="button" onClick={onClose}>Отмена</button><button className="button primary" onClick={submit} disabled={create.isPending||!printer||!spool}>{create.isPending?"Создаём…":"Добавить в очередь"}</button></div></div>
    <aside className="cost-summary"><p className="eyebrow">РАСЧЁТ СЕБЕСТОИМОСТИ</p><h2>{printer?.manufacturer} {printer?.name}</h2><div className="cost-lines"><div><span>Пластик · {values.grams} г</span><strong>{money(cost.material)}</strong></div><div className="electricity"><span><Zap size={13}/> Электричество · {cost.energy.toFixed(3)} кВт·ч</span><strong>{money(cost.electricity)}</strong></div><div><span>Станок + амортизация</span><strong>{money(cost.machine)}</strong></div><div><span>Работа оператора</span><strong>{money(cost.labour)}</strong></div><div><span>Постобработка</span><strong>{money(values.post)}</strong></div><div><span>Упаковка</span><strong>{money(values.packaging)}</strong></div><div><span>Прочее</span><strong>{money(values.other)}</strong></div></div><div className="cost-total"><span>Себестоимость</span><strong>{money(cost.total)}</strong></div><div className="suggested"><span>Цена с наценкой {values.markup}%</span><strong>{money(cost.price)}</strong></div><p style={{fontSize:10,color:"#aab6af",marginTop:14}}>Свет: {printer?.powerWatts??0} Вт × {(values.minutes/60).toFixed(2)} ч × {config?.electricityPricePerKwh??0} MDL/кВт·ч</p></aside>
  </div>;
}
