"use client";
import { useQuery } from "@tanstack/react-query";
import Link from "next/link";
import { api, money } from "@/lib/api";
import { PageHeader, Status } from "@/components/ui";
import { ArrowUpRight, Box, CircleDollarSign, Clock3, Layers3, PackageOpen, Printer, Zap } from "lucide-react";

type Dashboard={activeOrders:number;queuedJobs:number;printingPrinters:number;idlePrinters:number;maintenancePrinters:number;spoolCount:number;filamentGrams:number;stockValue:number;monthlyRevenue:number;monthlyProductionCost:number;monthlyProfit:number;monthlyElectricityCost:number;printers:{id:string;name:string;manufacturer:string;status:string;orderNumber?:string;modelName?:string}[]};
export default function DashboardPage(){const q=useQuery({queryKey:["dashboard"],queryFn:()=>api<Dashboard>("/api/dashboard")});const d=q.data;const today=new Intl.DateTimeFormat("ru-MD",{day:"numeric",month:"long",year:"numeric"}).format(new Date()).toUpperCase();return <><PageHeader eyebrow={today} title="Добрый день, Administrator" description="Вот что происходит в мастерской прямо сейчас." actions={<Link className="button primary" href="/orders"><Box size={17}/> Новый заказ</Link>}/><section className="metric-grid"><Metric icon={<Layers3/>} label="Активные заказы" value={d?.activeOrders??"—"} note="Все незавершённые заказы" tone="violet"/><Metric icon={<Clock3/>} label="В очереди" value={d?.queuedJobs??"—"} note="Ожидают запуска" tone="blue"/><Metric icon={<Printer/>} label="Сейчас печатают" value={d?.printingPrinters??"—"} note={`${d?.idlePrinters??0} свободно`} tone="green"/><Metric icon={<PackageOpen/>} label="Остаток пластика" value={d?`${(d.filamentGrams/1000).toFixed(1)} кг`:"—"} note={`${d?.spoolCount??0} активных катушек`} tone="orange"/></section><section className="dashboard-grid"><div className="panel span-2"><div className="panel-title"><div><p className="eyebrow">ПРОИЗВОДСТВО</p><h2>Состояние принтеров</h2></div><Link href="/printers">Все принтеры <ArrowUpRight size={15}/></Link></div><div className="printer-list">{d?.printers?.map(p=><div className="printer-row" key={p.id}><div className="printer-avatar"><Printer size={21}/></div><div className="grow"><strong>{p.manufacturer} {p.name}</strong><small>{p.modelName||p.orderNumber||"Нет активного задания"}</small></div><Status value={p.status}/><div className="progress-box"><div><span>{p.status==="PRINTING"?"В работе":"—"}</span><small>{p.status==="PRINTING"?"Активное задание":"Ожидает задания"}</small></div></div></div>)}</div></div><div className="panel money-panel"><div className="panel-title"><div><p className="eyebrow">ФИНАНСЫ · ТЕКУЩИЙ МЕСЯЦ</p><h2>Деньги мастерской</h2></div><CircleDollarSign/></div><div className="hero-money"><span>Оборот</span><strong>{money(d?.monthlyRevenue??0)}</strong></div><div className="money-lines"><div><span>Себестоимость</span><strong>{money(d?.monthlyProductionCost??0)}</strong></div><div className="energy-line"><span><Zap size={14}/> Электричество</span><strong>{money(d?.monthlyElectricityCost??0)}</strong></div><div><span>Прибыль</span><strong className="positive">{money(d?.monthlyProfit??0)}</strong></div></div></div></section><section className="insight-row"><div><span className="insight-icon"><Zap/></span><p><strong>Энергия под контролем</strong><small>Тариф учитывается в каждом задании печати.</small></p></div><strong>{money(d?.monthlyElectricityCost??0)} <small>за месяц</small></strong></section></>}
function Metric({icon,label,value,note,tone}:{icon:React.ReactNode;label:string;value:string|number;note:string;tone:string}){return <div className="metric"><span className={`metric-icon ${tone}`}>{icon}</span><div><p>{label}</p><strong>{value}</strong><small>{note}</small></div></div>}
