"use client";

import { open } from "@tauri-apps/plugin-dialog";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Box, Calculator, CalendarDays, ChevronRight, CircleDollarSign, Database, FileBox, FolderOpen, Gauge, HardDrive, LayoutDashboard, LoaderCircle, PackageOpen, Plus, Printer, ReceiptText, RefreshCw, Save, Search, Settings2, ShoppingBag, Sparkles, Upload, Users, Wrench, Zap } from "lucide-react";
import { AppInfo, CostBreakdown, CostInput, Customer, Dashboard, desktop, ModelAsset, NewPrintJob, Order, PrintJob, Printer as PrinterType, PrinterCatalogModel, Settings, Spool } from "@/lib/desktop";

type Section = "dashboard" | "orders" | "customers" | "models" | "production" | "equipment" | "catalog" | "calculator" | "settings";

const initialCost: CostInput = { printMinutes:270, filamentGrams:184, filamentPricePerGram:.45, powerWatts:120, electricityPricePerKwh:2.58, machineRatePerHour:25, depreciationPerHour:5, operatorHours:.5, labourRatePerHour:50, postProcessingCost:0, packagingCost:10, otherCost:0, markupPercent:40 };
const statuses = ["NEW","CONFIRMED","WAITING","READY_TO_PRINT","PRINTING","POST_PROCESSING","READY","COMPLETED","CANCELLED"];
const statusLabel:Record<string,string> = { NEW:"Новый", CONFIRMED:"Подтверждён", WAITING:"Ожидает", READY_TO_PRINT:"К печати", PRINTING:"Печатается", POST_PROCESSING:"Обработка", READY:"Готов", COMPLETED:"Выдан", CANCELLED:"Отменён", IDLE:"Свободен", QUEUED:"В очереди" };

export default function DesktopPage() {
  const [section,setSection] = useState<Section>("dashboard");
  const [dashboard,setDashboard] = useState<Dashboard>();
  const [orders,setOrders] = useState<Order[]>([]);
  const [customers,setCustomers] = useState<Customer[]>([]);
  const [printers,setPrinters] = useState<PrinterType[]>([]);
  const [spools,setSpools] = useState<Spool[]>([]);
  const [models,setModels] = useState<ModelAsset[]>([]);
  const [jobs,setJobs] = useState<PrintJob[]>([]);
  const [catalog,setCatalog] = useState<PrinterCatalogModel[]>([]);
  const [settings,setSettings] = useState<Settings>();
  const [appInfo,setAppInfo] = useState<AppInfo>();
  const [costInput,setCostInput] = useState<CostInput>(initialCost);
  const [cost,setCost] = useState<CostBreakdown>();
  const [error,setError] = useState("");
  const [notice,setNotice] = useState("");
  const [loading,setLoading] = useState(true);
  const [newOrder,setNewOrder] = useState({customerId:"",title:"",sellingPrice:0,paidAmount:0,deadline:"",notes:""});

  const refresh = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const [summary,orderRows,customerRows,printerRows,spoolRows,modelRows,jobRows,catalogRows,currentSettings,info] = await Promise.all([desktop.dashboard(),desktop.orders(),desktop.customers(),desktop.printers(),desktop.spools(),desktop.models(),desktop.printJobs(),desktop.printerCatalog(),desktop.settings(),desktop.appInfo()]);
      setDashboard(summary); setOrders(orderRows); setCustomers(customerRows); setPrinters(printerRows); setSpools(spoolRows); setModels(modelRows); setJobs(jobRows); setCatalog(catalogRows); setSettings(currentSettings); setAppInfo(info);
      setCostInput(value => ({...value,electricityPricePerKwh:currentSettings.electricityPricePerKwh,machineRatePerHour:currentSettings.machineRatePerHour,labourRatePerHour:currentSettings.labourRatePerHour,markupPercent:currentSettings.defaultMarkupPercent}));
    } catch (reason) { setError(String(reason)); }
    finally { setLoading(false); }
  },[]);

  useEffect(() => { const task=window.setTimeout(()=>void refresh(),0); return ()=>window.clearTimeout(task); },[refresh]);
  useEffect(() => { desktop.calculateCost(costInput).then(setCost).catch(reason => setError(String(reason))); },[costInput]);

  async function createOrder(event:FormEvent) {
    event.preventDefault(); setError("");
    try { await desktop.createOrder({customerId:newOrder.customerId||undefined,title:newOrder.title,deadline:newOrder.deadline||undefined,sellingPrice:newOrder.sellingPrice,paidAmount:newOrder.paidAmount,notes:newOrder.notes||undefined}); setNewOrder({customerId:"",title:"",sellingPrice:0,paidAmount:0,deadline:"",notes:""}); setNotice("Заказ создан, код отслеживания сохранён."); await refresh(); }
    catch (reason) { setError(String(reason)); }
  }
  async function changeStatus(id:string,status:string) { try { await desktop.updateOrderStatus(id,status); await refresh(); } catch (reason) { setError(String(reason)); } }
  async function createReceipt(id:string) { try { const result=await desktop.generateReceipt(id); setNotice(`PDF создан: ${result.filename}`); } catch (reason) { setError(String(reason)); } }
  async function saveSettings(event:FormEvent) { event.preventDefault(); if (!settings) return; try { setSettings(await desktop.saveSettings(settings)); setNotice("Настройки сохранены в локальной SQLite."); await refresh(); } catch (reason) { setError(String(reason)); } }

  const title = useMemo(() => ({dashboard:"Обзор мастерской",orders:"Заказы и квитанции",customers:"Клиенты",models:"Библиотека моделей",production:"Очередь производства",equipment:"Оборудование и склад",catalog:"Каталог принтеров 2026",calculator:"Расчёт себестоимости",settings:"Настройки и данные"})[section],[section]);

  return <main className="desktop-shell">
    <aside className="desktop-sidebar">
      <div className="desktop-brand"><span>3D</span><div><strong>PrintForge</strong><small>Desktop · local admin</small></div></div>
      <nav>
        <Nav active={section==="dashboard"} icon={LayoutDashboard} label="Обзор" onClick={()=>setSection("dashboard")}/>
        <Nav active={section==="orders"} icon={ShoppingBag} label="Заказы" onClick={()=>setSection("orders")} badge={orders.length}/>
        <Nav active={section==="customers"} icon={Users} label="Клиенты" onClick={()=>setSection("customers")} badge={customers.length}/>
        <Nav active={section==="models"} icon={FileBox} label="Модели" onClick={()=>setSection("models")} badge={models.length}/>
        <Nav active={section==="production"} icon={CalendarDays} label="Производство" onClick={()=>setSection("production")} badge={jobs.filter(job=>job.status!=="COMPLETED").length}/>
        <Nav active={section==="equipment"} icon={Wrench} label="Принтеры и склад" onClick={()=>setSection("equipment")}/>
        <Nav active={section==="catalog"} icon={Search} label="Каталог 2026" onClick={()=>setSection("catalog")} badge={catalog.length}/>
        <Nav active={section==="calculator"} icon={Calculator} label="Себестоимость" onClick={()=>setSection("calculator")}/>
        <Nav active={section==="settings"} icon={Settings2} label="Настройки" onClick={()=>setSection("settings")}/>
      </nav>
      <div className="desktop-local"><Database/><div><strong>Без авторизации</strong><span>SQLite · только на устройстве</span></div><i/></div>
    </aside>
    <section className="desktop-main">
      <header className="desktop-topbar"><div><p>PRINTFORGE DESKTOP / RUST</p><h1>{title}</h1></div><button className="icon-action" onClick={()=>void refresh()} title="Обновить"><RefreshCw className={loading?"spin":""}/></button></header>
      {notice&&<div className="desktop-notice"><Sparkles/><span>{notice}</span><button onClick={()=>setNotice("")}>×</button></div>}
      {error&&<div className="desktop-error"><HardDrive/><div><strong>Rust-команда вернула ошибку</strong><p>{error}</p><small>В dev-режиме подробности также видны в терминале.</small></div></div>}
      {loading&&!dashboard?<div className="desktop-loading"><LoaderCircle className="spin"/>Инициализация Rust core и SQLite…</div>:<div className="desktop-content">
        {section==="dashboard"&&<DashboardView dashboard={dashboard} orders={orders} printers={printers} spools={spools} jobs={jobs}/>}
        {section==="orders"&&<OrdersView customers={customers} newOrder={newOrder} orders={orders} currency={settings?.currency||"MDL"} setNewOrder={setNewOrder} createOrder={createOrder} changeStatus={changeStatus} createReceipt={createReceipt}/>}
        {section==="customers"&&<CustomersView customers={customers} onChanged={refresh} onError={setError}/>}
        {section==="models"&&<ModelsView models={models} customers={customers} onChanged={refresh} onError={setError}/>}
        {section==="production"&&<ProductionView jobs={jobs} orders={orders} printers={printers} spools={spools} currency={settings?.currency||"MDL"} onChanged={refresh} onError={setError}/>}
        {section==="equipment"&&<EquipmentView printers={printers} spools={spools} onChanged={refresh} onError={setError}/>}
        {section==="catalog"&&<CatalogView catalog={catalog} onChanged={refresh} onError={setError}/>}
        {section==="calculator"&&<CalculatorView cost={cost} input={costInput} setInput={setCostInput} currency={settings?.currency||"MDL"}/>}
        {section==="settings"&&settings&&<SettingsView settings={settings} setSettings={setSettings} save={saveSettings} appInfo={appInfo}/>}
      </div>}
    </section>
  </main>;
}

function Nav({active,icon:Icon,label,onClick,badge}:{active:boolean;icon:typeof Gauge;label:string;onClick:()=>void;badge?:number}) { return <button className={active?"active":""} onClick={onClick}><Icon/><span>{label}</span>{badge!==undefined&&<em>{badge}</em>}</button>; }

function DashboardView({dashboard,orders,printers,spools,jobs}:{dashboard?:Dashboard;orders:Order[];printers:PrinterType[];spools:Spool[];jobs:PrintJob[]}) {
  const currency=dashboard?.currency||"MDL";
  return <><div className="desktop-metrics"><Metric icon={ShoppingBag} label="Активные заказы" value={dashboard?.activeOrders??0} tone="violet"/><Metric icon={Printer} label="Свободные принтеры" value={dashboard?.availablePrinters??0} tone="green"/><Metric icon={CircleDollarSign} label="Оборот" value={`${money(dashboard?.revenue||0)} ${currency}`} tone="amber"/><Metric icon={Zap} label="Осталось оплатить" value={`${money(dashboard?.outstanding||0)} ${currency}`} tone="blue"/></div><div className="desktop-grid"><section className="desktop-panel wide"><PanelTitle eyebrow="В ПРОИЗВОДСТВЕ" title="Последние заказы"/><div className="order-list">{orders.length?orders.slice(0,5).map(order=><div className="order-line" key={order.id}><div className="order-code"><span>{order.number.slice(-2)}</span></div><div className="grow"><strong>{order.title}</strong><small>{order.customerName} · {order.trackingCode}</small></div><Status value={order.status}/><strong>{money(order.sellingPrice)} {currency}</strong></div>):<Empty text="Первый заказ можно создать в разделе «Заказы»"/>}</div></section><section className="desktop-panel"><PanelTitle eyebrow="СТАНКИ" title="Состояние парка"/><div className="compact-list">{printers.map(printer=><div key={printer.id}><span className="printer-dot"/><p><strong>{printer.name}</strong><small>{printer.manufacturer} · {printer.powerWatts} Вт</small></p><Status value={printer.status}/></div>)}</div></section></div><div className="desktop-insight"><Sparkles/><div><strong>Всё локально: Rust + SQLite</strong><p>Заказы, {jobs.length} заданий, модели и расчёты работают без Go API, Docker и интернета.</p></div><span>{spools.reduce((sum,spool)=>sum+spool.remainingGrams,0).toFixed(0)} г пластика</span></div></>;
}

function OrdersView({customers,newOrder,setNewOrder,orders,currency,createOrder,changeStatus,createReceipt}:{customers:Customer[];newOrder:{customerId:string;title:string;sellingPrice:number;paidAmount:number;deadline:string;notes:string};setNewOrder:React.Dispatch<React.SetStateAction<typeof newOrder>>;orders:Order[];currency:string;createOrder:(e:FormEvent)=>void;changeStatus:(id:string,status:string)=>void;createReceipt:(id:string)=>void}) {
  return <div className="orders-layout"><form className="desktop-panel order-form" onSubmit={createOrder}><PanelTitle eyebrow="НОВЫЙ ЗАКАЗ" title="Добавить в локальную базу"/><label>Клиент<select value={newOrder.customerId} onChange={e=>setNewOrder(v=>({...v,customerId:e.target.value}))}><option value="">Без клиента</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Название заказа<input required value={newOrder.title} onChange={e=>setNewOrder(v=>({...v,title:e.target.value}))} placeholder="Корпус редуктора"/></label><div className="two-fields"><label>Цена, {currency}<input type="number" min="0" step="0.01" value={newOrder.sellingPrice} onChange={e=>setNewOrder(v=>({...v,sellingPrice:Number(e.target.value)}))}/></label><label>Оплачено<input type="number" min="0" step="0.01" value={newOrder.paidAmount} onChange={e=>setNewOrder(v=>({...v,paidAmount:Number(e.target.value)}))}/></label></div><label>Срок<input type="datetime-local" value={newOrder.deadline} onChange={e=>setNewOrder(v=>({...v,deadline:e.target.value}))}/></label><label>Заметка<textarea value={newOrder.notes} onChange={e=>setNewOrder(v=>({...v,notes:e.target.value}))}/></label><button className="primary-action"><Plus/>Создать заказ</button></form><section className="desktop-panel"><PanelTitle eyebrow="ЛОКАЛЬНЫЕ ДАННЫЕ" title={`${orders.length} заказов`}/><div className="order-cards">{orders.map(order=><article key={order.id}><header><div><small>{order.number}</small><h3>{order.title}</h3><p>{order.customerName}</p></div><Status value={order.status}/></header><div className="tracking-chip">Код <strong>{order.trackingCode}</strong></div><footer><span>{money(order.paidAmount)} / {money(order.sellingPrice)} {currency}</span><button className="mini-action" onClick={()=>void createReceipt(order.id)} title="Создать PDF"><ReceiptText/>PDF</button><select value={order.status} onChange={e=>void changeStatus(order.id,e.target.value)}>{statuses.map(s=><option value={s} key={s}>{statusLabel[s]}</option>)}</select></footer></article>)}{!orders.length&&<Empty text="Заказов пока нет"/>}</div></section></div>;
}

function CustomersView({customers,onChanged,onError}:{customers:Customer[];onChanged:()=>Promise<void>;onError:(value:string)=>void}) {
  const [form,setForm]=useState({name:"",company:"",phone:"",email:""});
  async function submit(event:FormEvent){event.preventDefault();try{await desktop.createCustomer({name:form.name,company:form.company||undefined,phone:form.phone||undefined,email:form.email||undefined});setForm({name:"",company:"",phone:"",email:""});await onChanged();}catch(reason){onError(String(reason));}}
  return <div className="orders-layout"><form className="desktop-panel order-form" onSubmit={submit}><PanelTitle eyebrow="КЛИЕНТ" title="Новая карточка"/><label>Имя<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Компания<input value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/></label><label>Телефон<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><button className="primary-action"><Plus/>Добавить клиента</button></form><section className="desktop-panel"><PanelTitle eyebrow="БАЗА КЛИЕНТОВ" title={`${customers.length} записей`}/><div className="entity-grid">{customers.map(customer=><article key={customer.id}><div className="entity-icon"><Users/></div><h3>{customer.name}</h3><p>{customer.company||"Частный клиент"}</p><small>{customer.phone||"Телефон не указан"}<br/>{customer.email||"Email не указан"}</small></article>)}</div></section></div>;
}

function ModelsView({models,customers,onChanged,onError}:{models:ModelAsset[];customers:Customer[];onChanged:()=>Promise<void>;onError:(value:string)=>void}) {
  const [customerId,setCustomerId]=useState("");
  async function choose(){try{const selected=await open({multiple:false,filters:[{name:"3D models",extensions:["stl","obj","3mf","gcode","gco","gc"]}]});if(typeof selected!=="string")return;await desktop.importModel({sourcePath:selected,customerId:customerId||undefined});await onChanged();}catch(reason){onError(String(reason));}}
  return <><section className="desktop-panel model-toolbar"><div><PanelTitle eyebrow="STL · OBJ · 3MF · G-CODE" title="Локальная библиотека"/><p>Файл копируется в защищённую папку данных программы.</p></div><label>Владелец<select value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Без клиента</option>{customers.map(customer=><option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></label><button className="primary-action" onClick={()=>void choose()}><Upload/>Импортировать модель</button></section><div className="model-grid">{models.map(model=><article className="desktop-panel" key={model.id}><div className="file-tile"><Box/><span>{model.format}</span></div><h3>{model.name}</h3><p>{model.customerName}</p><small>{formatBytes(model.fileSizeBytes)}{model.estimatedPrintMinutes?` · ${model.estimatedPrintMinutes} мин`:""}{model.estimatedFilamentGrams?` · ${model.estimatedFilamentGrams} г`:""}</small><button className="secondary-action" onClick={()=>void desktop.revealModel(model.id)}><FolderOpen/>Показать файл</button></article>)}{!models.length&&<div className="desktop-panel"><Empty text="Импортируйте первую STL, 3MF или G-code модель"/></div>}</div></>;
}

function ProductionView({jobs,orders,printers,spools,currency,onChanged,onError}:{jobs:PrintJob[];orders:Order[];printers:PrinterType[];spools:Spool[];currency:string;onChanged:()=>Promise<void>;onError:(value:string)=>void}) {
  const [form,setForm]=useState<NewPrintJob>({printMinutes:60,filamentGrams:20,totalCost:0});
  async function submit(event:FormEvent){event.preventDefault();try{await desktop.createPrintJob(form);setForm({printMinutes:60,filamentGrams:20,totalCost:0});await onChanged();}catch(reason){onError(String(reason));}}
  async function complete(id:string){try{await desktop.completePrintJob(id);await onChanged();}catch(reason){onError(String(reason));}}
  return <div className="orders-layout"><form className="desktop-panel order-form" onSubmit={submit}><PanelTitle eyebrow="ПРОИЗВОДСТВО" title="Новое задание"/><label>Заказ<select value={form.orderId||""} onChange={e=>setForm({...form,orderId:e.target.value||undefined})}><option value="">Без заказа</option>{orders.map(order=><option key={order.id} value={order.id}>{order.number} · {order.title}</option>)}</select></label><label>Принтер<select value={form.printerId||""} onChange={e=>setForm({...form,printerId:e.target.value||undefined})}><option value="">Не выбран</option>{printers.map(printer=><option key={printer.id} value={printer.id}>{printer.name}</option>)}</select></label><label>Катушка<select value={form.spoolId||""} onChange={e=>setForm({...form,spoolId:e.target.value||undefined})}><option value="">Не выбрана</option>{spools.map(spool=><option key={spool.id} value={spool.id}>{spool.code} · {spool.material} · {spool.remainingGrams.toFixed(0)} г</option>)}</select></label><div className="two-fields"><label>Время, мин<input type="number" min="0" value={form.printMinutes} onChange={e=>setForm({...form,printMinutes:Number(e.target.value)})}/></label><label>Пластик, г<input type="number" min="0" step="0.01" value={form.filamentGrams} onChange={e=>setForm({...form,filamentGrams:Number(e.target.value)})}/></label></div><label>Себестоимость, {currency}<input type="number" min="0" step="0.01" value={form.totalCost} onChange={e=>setForm({...form,totalCost:Number(e.target.value)})}/></label><button className="primary-action"><Plus/>Добавить в очередь</button></form><section className="desktop-panel"><PanelTitle eyebrow="ОЧЕРЕДЬ" title={`${jobs.length} заданий`}/><div className="job-list">{jobs.map(job=><article key={job.id}><div><small>{job.orderNumber||"Без заказа"}</small><h3>{job.printerName||"Принтер не выбран"}</h3><p>{job.printMinutes} мин · {job.filamentGrams.toFixed(1)} г · {job.spoolCode||"без катушки"}</p></div><Status value={job.status}/>{job.status!=="COMPLETED"&&<button className="mini-action" onClick={()=>void complete(job.id)}>Завершить</button>}</article>)}{!jobs.length&&<Empty text="Очередь пока пуста"/>}</div></section></div>;
}

function EquipmentView({printers,spools,onChanged,onError}:{printers:PrinterType[];spools:Spool[];onChanged:()=>Promise<void>;onError:(value:string)=>void}) {
  const [form,setForm]=useState({code:"",manufacturer:"",productName:"",material:"PLA",colorName:"",colorHex:"#232825",initialGrams:1000,purchasePrice:0,supplier:""});
  async function addSpool(event:FormEvent){event.preventDefault();try{await desktop.createSpool({...form,supplier:form.supplier||undefined});setForm({...form,code:"",colorName:"",purchasePrice:0});await onChanged();}catch(reason){onError(String(reason));}}
  return <><div className="desktop-grid"><section className="desktop-panel wide"><PanelTitle eyebrow="ПРИНТЕРЫ" title={`${printers.length} единицы оборудования`}/><div className="equipment-grid">{printers.map(p=><article key={p.id}><div className="machine-visual"><Printer/></div><small>{p.manufacturer}</small><h3>{p.name}</h3><p>{p.model} · {p.powerWatts} Вт</p><Status value={p.status}/></article>)}</div></section><section className="desktop-panel"><PanelTitle eyebrow="СКЛАД" title="Катушки"/><div className="spool-list">{spools.map(s=><div key={s.id}><i style={{background:s.colorHex}}/><p><strong>{s.code} · {s.material}</strong><span>{s.colorName}</span></p><em>{s.remainingGrams.toFixed(0)} г</em></div>)}</div></section></div><form className="desktop-panel inline-create" onSubmit={addSpool}><PanelTitle eyebrow="СКЛАД" title="Добавить катушку"/><label>Код<input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></label><label>Производитель<input required value={form.manufacturer} onChange={e=>setForm({...form,manufacturer:e.target.value})}/></label><label>Серия<input required value={form.productName} onChange={e=>setForm({...form,productName:e.target.value})}/></label><label>Материал<select value={form.material} onChange={e=>setForm({...form,material:e.target.value})}>{["PLA","PETG","ABS","ASA","TPU","Nylon","PC","Resin"].map(value=><option key={value}>{value}</option>)}</select></label><label>Цвет<input required value={form.colorName} onChange={e=>setForm({...form,colorName:e.target.value})}/></label><label>Вес, г<input type="number" min="1" value={form.initialGrams} onChange={e=>setForm({...form,initialGrams:Number(e.target.value)})}/></label><label>Цена<input type="number" min="0" step="0.01" value={form.purchasePrice} onChange={e=>setForm({...form,purchasePrice:Number(e.target.value)})}/></label><button className="primary-action"><Plus/>Сохранить</button></form></>;
}

function CatalogView({catalog,onChanged,onError}:{catalog:PrinterCatalogModel[];onChanged:()=>Promise<void>;onError:(value:string)=>void}) {
  const [search,setSearch]=useState(""); const [brand,setBrand]=useState("ALL");
  const matches=useMemo(()=>catalog.filter(item=>(brand==="ALL"||item.manufacturer===brand)&&(`${item.manufacturer} ${item.model}`.toLowerCase().includes(search.toLowerCase()))).slice(0,120),[catalog,search,brand]);
  async function add(item:PrinterCatalogModel){try{await desktop.createPrinter({catalogKey:item.key,name:item.model,manufacturer:item.manufacturer,model:item.model,powerWatts:0,buildXMm:item.buildXMm,buildYMm:item.buildYMm,buildZMm:item.buildZMm,purchasePrice:0});await onChanged();}catch(reason){onError(String(reason));}}
  return <><section className="desktop-panel catalog-toolbar"><div><PanelTitle eyebrow="ORCASLICER + BAMBU STUDIO" title={`${catalog.length} профилей внутри установщика`}/><p>Актуальный снимок на 2026 год · работает без интернета.</p></div><div className="catalog-filters"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Найти модель…"/></label><select value={brand} onChange={e=>setBrand(e.target.value)}><option value="ALL">Все бренды</option><option>Bambu Lab</option><option>Creality</option><option>Anycubic</option></select></div></section><div className="catalog-grid">{matches.map(item=><article className="desktop-panel" key={item.key}><div className="catalog-image" style={item.imageUrl?{backgroundImage:`url("${item.imageUrl}")`}:undefined}><span>{item.technology}</span></div><small>{item.manufacturer}</small><h3>{item.model}</h3><p>{item.buildXMm||"—"} × {item.buildYMm||"—"} × {item.buildZMm||"—"} мм</p><div className="catalog-tags">{item.nozzleDiameters.slice(0,4).map(size=><i key={size}>{size} мм</i>)}</div><button className="secondary-action" onClick={()=>void add(item)}><Plus/>Добавить в мастерскую</button></article>)}</div></>;
}

function CalculatorView({input,setInput,cost,currency}:{input:CostInput;setInput:React.Dispatch<React.SetStateAction<CostInput>>;cost?:CostBreakdown;currency:string}) {
  const fields:[keyof CostInput,string,string][]=[["printMinutes","Время печати","мин"],["filamentGrams","Пластик","г"],["filamentPricePerGram","Цена грамма",currency],["powerWatts","Мощность","Вт"],["electricityPricePerKwh","Тариф света",`${currency}/кВт·ч`],["machineRatePerHour","Ставка станка",`${currency}/ч`],["depreciationPerHour","Амортизация",`${currency}/ч`],["operatorHours","Работа оператора","ч"],["labourRatePerHour","Ставка оператора",`${currency}/ч`],["postProcessingCost","Постобработка",currency],["packagingCost","Упаковка",currency],["otherCost","Прочее",currency],["markupPercent","Наценка","%"]];
  return <div className="calculator-layout"><section className="desktop-panel"><PanelTitle eyebrow="ПАРАМЕТРЫ" title="Все вычисления выполняет Rust"/><div className="calculator-fields">{fields.map(([key,label,suffix])=><label key={key}><span>{label}</span><div><input type="number" min="0" step="0.01" value={input[key]} onChange={e=>setInput(v=>({...v,[key]:Number(e.target.value)}))}/><em>{suffix}</em></div></label>)}</div></section><aside className="cost-result"><p>РАСЧЁТ СЕБЕСТОИМОСТИ</p><h2>{cost?money(cost.suggestedPrice):"—"} <small>{currency}</small></h2><div className="energy-result"><Zap/>Электричество · {cost?.energyKwh.toFixed(3)||"0"} кВт·ч</div>{cost&&<div className="cost-lines"><CostLine label="Пластик" value={cost.materialCost}/><CostLine label="Электричество" value={cost.electricityCost}/><CostLine label="Станок" value={cost.machineCost}/><CostLine label="Амортизация" value={cost.depreciationCost}/><CostLine label="Оператор" value={cost.labourCost}/><CostLine label="Дополнительные расходы" value={cost.postProcessingCost+cost.packagingCost+cost.otherCost}/><CostLine label="Себестоимость" value={cost.totalCost} strong/><CostLine label="Наценка" value={cost.markupAmount}/></div>}<div className="rust-badge"><span>R</span> rust_decimal · точное округление</div></aside></div>;
}

function SettingsView({settings,setSettings,save,appInfo}:{settings:Settings;setSettings:(s:Settings)=>void;save:(e:FormEvent)=>void;appInfo?:AppInfo}) { return <><form className="desktop-panel settings-form" onSubmit={save}><PanelTitle eyebrow="RUST + SQLITE" title="Настройки мастерской"/><div className="settings-grid"><label>Название мастерской<input value={settings.companyName} onChange={e=>setSettings({...settings,companyName:e.target.value})}/></label><label>Валюта<input maxLength={3} value={settings.currency} onChange={e=>setSettings({...settings,currency:e.target.value.toUpperCase()})}/></label><label>Тариф за кВт·ч<input type="number" min="0" step="0.0001" value={settings.electricityPricePerKwh} onChange={e=>setSettings({...settings,electricityPricePerKwh:Number(e.target.value)})}/></label><label>Ставка станка / ч<input type="number" min="0" value={settings.machineRatePerHour} onChange={e=>setSettings({...settings,machineRatePerHour:Number(e.target.value)})}/></label><label>Ставка оператора / ч<input type="number" min="0" value={settings.labourRatePerHour} onChange={e=>setSettings({...settings,labourRatePerHour:Number(e.target.value)})}/></label><label>Наценка по умолчанию, %<input type="number" min="0" value={settings.defaultMarkupPercent} onChange={e=>setSettings({...settings,defaultMarkupPercent:Number(e.target.value)})}/></label><label>Низкий остаток, г<input type="number" min="0" value={settings.lowStockThresholdGrams} onChange={e=>setSettings({...settings,lowStockThresholdGrams:Number(e.target.value)})}/></label></div><button className="primary-action"><Save/>Сохранить в SQLite</button></form><section className="desktop-panel data-card"><div><PanelTitle eyebrow="ЛОКАЛЬНЫЙ BACKEND" title="Данные приложения"/><p>SQLite, импортированные модели и PDF-квитанции хранятся здесь и переживают обновление программы.</p><code>{appInfo?.dataDirectory||"—"}</code><small>База: {appInfo?.databasePath||"—"} · v{appInfo?.appVersion||"—"} · {appInfo?.catalogModels||0} профилей</small></div><button className="secondary-action" onClick={()=>void desktop.openDataDirectory()}><FolderOpen/>Открыть папку</button></section></>; }

function Metric({icon:Icon,label,value,tone}:{icon:typeof Gauge;label:string;value:string|number;tone:string}) { return <article className="desktop-metric"><div className={tone}><Icon/></div><p>{label}<strong>{value}</strong></p><ChevronRight/></article>; }
function PanelTitle({eyebrow,title}:{eyebrow:string;title:string}) { return <header className="panel-heading"><div><p>{eyebrow}</p><h2>{title}</h2></div><span>•••</span></header>; }
function Status({value}:{value:string}) { return <span className={`desktop-status ${value.toLowerCase()}`}><i/>{statusLabel[value]||value}</span>; }
function CostLine({label,value,strong=false}:{label:string;value:number;strong?:boolean}) { return <div className={strong?"strong":""}><span>{label}</span><b>{money(value)}</b></div>; }
function Empty({text}:{text:string}) { return <div className="desktop-empty"><PackageOpen/><span>{text}</span></div>; }
function money(value:number) { return new Intl.NumberFormat("ru-RU",{minimumFractionDigits:2,maximumFractionDigits:2}).format(value); }
function formatBytes(value:number) { if(value<1024)return `${value} Б`; if(value<1024*1024)return `${(value/1024).toFixed(1)} КБ`; return `${(value/1024/1024).toFixed(1)} МБ`; }
